// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaLocacao;

#nullable disable

namespace SistemaLocacaoFinal.Migrations
{
    [DbContext(typeof(BancoDeDados))]
    [Migration("20221106174742_NovoDB")]
    partial class NovoDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("SistemaLocacao.Imovel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("bairro")
                        .HasColumnType("TEXT");

                    b.Property<string>("cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("complemento")
                        .HasColumnType("TEXT");

                    b.Property<string>("disponivel")
                        .HasColumnType("TEXT");

                    b.Property<string>("endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("estado")
                        .HasColumnType("TEXT");

                    b.Property<string>("numero")
                        .HasColumnType("TEXT");

                    b.Property<string>("proprietario")
                        .HasColumnType("TEXT");

                    b.Property<string>("valorAluguel")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Imoveis");
                });

            modelBuilder.Entity("SistemaLocacao.Locacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("dataLocacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("emailLocatario")
                        .HasColumnType("TEXT");

                    b.Property<int>("idImovel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idLocatario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("proprietarioImovel")
                        .HasColumnType("TEXT");

                    b.Property<string>("tempoContrato")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Locacoes");
                });

            modelBuilder.Entity("SistemaLocacao.Locatario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Locatarios");
                });
#pragma warning restore 612, 618
        }
    }
}
